<?php

namespace app\v1\controller;

use think\Controller;
use think\Request;
class  AdminBase extends Controller
{
   protected  $post = '';

   protected  $get  = '';

   protected  $ajax = '';

   protected  $path = '';

   public function _initialize()
   {
       parent::_initialize(); // TODO: Change the autogenerated stub
       $this->post = Request::instance()->isPost();
       $this->get  = Request::instance()->isGet();
       $this->ajax = Request::instance()->isAjax();
       $this->path = Request::instance()->baseUrl(); //获取路由地址

       $this->assign('path',$this->path);

       $this->check_member();

   }


   public function check_member(){
       if(session('admin_user') == false || $this->request->action() =='out'){
           return $this->redirect('login/index');
       }
   }

}