<?php

namespace  app\index\controller;

use think\Controller;

class HomeBase extends Controller{


    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

}