<?php

namespace  app\index\controller;

use think\Controller;
use app\v1\model\Config;
use app\v1\model\Order;
class HomeBase extends Controller{

    protected  $model ='';

    protected  $order='';

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->order = new Order();
        //读取网站设置
        $this->model = new Config();
        $config = $this->model->getallone();
        $this->assign('config',$config);
    }



}